export const LOAD_ACTION_FORMS = "LOAD_ACTION_FORMS";
export const ADD_ACTION_FORM = "ADD_ACTION_FORM";
export const REMOVE_ACTION_FORM = "REMOVE_ACTION_FORM";
export const REORDER_ACTION_FORM = "REORDER_ACTION_FORM";
export const CLEAR_ACTION_FORMS = "CLEAR_ACTION_FORMS";
