//entities
export const FETCH_ENTITY = "FETCH_ENTITY";
export const RECIEVE_ENTITIES = "RECIEVE_ENTITIES";
export const UPDATE_ENTITY_REQUEST = "UPDATE_ENTITY_REQUEST";
export const CREATE_ENTITY_REQUEST = "CREATE_ENTITY_REQUEST";
export const DELETE_STEP_REQUEST = "DELETE_STEP_REQUEST";
export const DELETE_STEP_REQUEST__SUCCESS = "DELETE_STEP_REQUEST__SUCCESS";
export const REORDER_STEP_REQUEST = "REORDER_STEP_REQUEST";

//form
export const SET_STEP = "SET_STEP";
export const SET_IMAGE = "SET_IMAGE";
export const CLEAR_FORM = "CLEAR_FORM";
export const SET_IMAGES = "SET_IMAGES";
export const STEP_SUBMIT_CLICK = "STEP_SUBMIT_CLICK";
export const INSERT_IMAGE = "INSERT_IMAGE";
export const DELETE_STEP_VISUALS = "DELETE_STEP_VISUALS";
export const REMOVE_IMAGE_AND_REORDER_STEP = "REMOVE_IMAGE_AND_REORDER_STEP";

export const REORDER_IMAGE = "REORDER_IMAGE";
export const ADD_IMAGE = "ADD_IMAGE";
export const UPDATE_IMAGE = "UPDATE_IMAGE";
export const REMOVE_IMAGE = "REMOVE_IMAGE";
export const REINDEX_IMAGES = "REINDEX_IMAGES";


//meta
export const SET_ENTITY_META = "SET_ENTITY_META";


//user
export const LOGOUT = "LOGOUT";





//toast
export const ADD_TOAST = 'ADD_TOAST';
export const REMOVE_TOAST = 'REMOVE_TOAST';

export const RECEIVE_ENTITIES = "RECEIVE_ENTITIES";



export const MOUNT_FORM = "MOUNT_FORM";
export const UNMOUNT_FORM = "UNMOUNT_FORM";

export const CREATE_AUTH_REQUEST = "CREATE_AUTH_REQUEST";
export const CREATE_AUTH_REQUEST__SUCCESS = "CREATE_AUTH_REQUEST__SUCCESS";
export const CREATE_AUTH_REQUEST__FAILURE = "CREATE_AUTH_REQUEST__FAILURE";

export const CREATE_OEM_REQUEST = "CREATE_OEM_REQUEST";
export const CREATE_OEM_REQUEST__SUCCESS = "CREATE_OEM_REQUEST__SUCCESS";
export const CREATE_OEM_REQUEST__FAILURE = "CREATE_OEM_REQUEST__FAILURE";

export const CREATE_BUSINESS_REQUEST = "CREATE_BUSINESS_REQUEST";
export const CREATE_BUSINESS_REQUEST__SUCCESS = "CREATE_BUSINESS_REQUEST__SUCCESS";
export const CREATE_BUSINESS_REQUEST__FAILURE = "CREATE_BUSINESS_REQUEST__FAILURE";

export const FETCH_OEMS_REQUEST = "FETCH_OEMS_REQUEST";
export const FETCH_OEMS_REQUEST__SUCCESS = "FETCH_OEMS_REQUEST__SUCCESS";
export const FETCH_OEMS_REQUEST__FAILURE = "FETCH_OEMS_REQUEST__FAILURE";

export const FETCH_OEM_BUSINESSES_REQUEST = "FETCH_OEM_BUSINESSES_REQUEST";
export const FETCH_OEM_BUSINESSES_REQUEST__SUCCESS = "FETCH_OEM_BUSINESSES_REQUEST__SUCCESS";
export const FETCH_OEM_BUSINESSES_REQUEST__FAILURE = "FETCH_OEM_BUSINESSES_REQUEST__FAILURE";

export const FETCH_BUSINESS_PROCEDURES_REQUEST = "FETCH_BUSINESS_PROCEDURES_REQUEST";
export const FETCH_BUSINESS_PROCEDURES_REQUEST__SUCCESS = "FETCH_BUSINESS_PROCEDURES_REQUEST__SUCCESS";
export const FETCH_BUSINESS_PROCEDURES_REQUEST__FAILURE = "FETCH_BUSINESS_PROCEDURES_REQUEST__FAILURE";

export const CREATE_INVITE_CONFIRMATION_REQUEST = "CREATE_INVITE_CONFIRMATION_REQUEST";
export const CREATE_INVITE_CONFIRMATION_REQUEST__SUCCESS = "CREATE_INVITE_CONFIRMATION_REQUEST__SUCCESS";
export const CREATE_INVITE_CONFIRMATION_REQUEST__FAILURE = "CREATE_INVITE_CONFIRMATION_REQUEST__FAILURE";

export const CREATE_PASSWORD_RESET_EMAIL_REQUEST = "CREATE_PASSWORD_RESET_EMAIL_REQUEST";
export const CREATE_PASSWORD_RESET_EMAIL_REQUEST__SUCCESS = "CREATE_PASSWORD_RESET_EMAIL_REQUEST__SUCCESS";
export const CREATE_PASSWORD_RESET_EMAIL_REQUEST__FAILURE = "CREATE_PASSWORD_RESET_EMAIL_REQUEST__FAILURE";

export const UPDATE_OEM_REQUEST = "UPDATE_OEM_REQUEST";
export const UPDATE_OEM_REQUEST__SUCCESS = "UPDATE_OEM_REQUEST__SUCCESS";
export const UPDATE_OEM_REQUEST__FAILURE = "UPDATE_OEM_REQUEST__FAILURE";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_REQUEST__SUCCESS = "UPDATE_PASSWORD_REQUEST__SUCCESS";
export const UPDATE_PASSWORD_REQUEST__FAILURE = "UPDATE_PASSWORD_REQUEST__FAILURE";

export const CREATE_PROCEDURE_REQUEST = "CREATE_PROCEDURE_REQUEST";
export const CREATE_PROCEDURE_REQUEST__SUCCESS = "CREATE_PROCEDURE_REQUEST__SUCCESS";
export const CREATE_PROCEDURE_REQUEST__FAILURE = "CREATE_PROCEDURE_REQUEST__FAILURE";

export const UPDATE_PROCEDURE_REQUEST = "UPDATE_PROCEDURE_REQUEST";
export const UPDATE_PROCEDURE_REQUEST__SUCCESS = "UPDATE_PROCEDURE_REQUEST__SUCCESS";
export const UPDATE_PROCEDURE_REQUEST__FAILURE = "UPDATE_PROCEDURE_REQUEST__FAILURE";

export const CREATE_STEP_REQUEST = "CREATE_STEP_REQUEST";
export const CREATE_STEP_REQUEST__SUCCESS = "CREATE_STEP_REQUEST__SUCCESS";
export const CREATE_STEP_REQUEST__FAILURE = "CREATE_STEP_REQUEST__FAILURE";

export const UPDATE_STEP_REQUEST = "UPDATE_STEP_REQUEST";
export const UPDATE_STEP_REQUEST__SUCCESS = "UPDATE_STEP_REQUEST__SUCCESS";
export const UPDATE_STEP_REQUEST__FAILURE = "UPDATE_STEP_REQUEST__FAILURE";

export const FETCH_PROCEDURE_REQUEST = "FETCH_PROCEDURE_REQUEST";
export const FETCH_PROCEDURE_REQUEST__SUCCESS = "FETCH_PROCEDURE_REQUEST__SUCCESS";
export const FETCH_PROCEDURE_REQUEST__FAILURE = "FETCH_PROCEDURE_REQUEST__FAILURE";

export const ADD_STEP_FORM = "ADD_STEP_FORM";
export const REMOVE_STEP_FORM = "REMOVE_STEP_FORM";
export const STEP_SAVE_REQUEST = "STEP_SAVE_REQUEST";
export const STEP_SAVE_REQUEST__FAILURE = "STEP_SAVE_REQUEST__FAILURE";
export const SET_CURRENT_STEP_FORM = "SET_CURRENT_STEP_FORM";

export const REORDER_STEP_REQUEST__SUCCESS = "REORDER_STEP_REQUEST__SUCCESS";

export const REMOVE_IMAGE_AND_REINDEX = "REMOVE_IMAGE_AND_REINDEX";
