//entities
export const FETCH_ENTITY = "FETCH_ENTITY";
export const RECIEVE_ENTITIES = "RECIEVE_ENTITIES";
export const UPDATE_ENTITY_REQUEST = "UPDATE_ENTITY_REQUEST";
export const CREATE_ENTITY_REQUEST = "CREATE_ENTITY_REQUEST";
export const DELETE_STEP_REQUEST = "DELETE_STEP_REQUEST";
export const DELETE_STEP_REQUEST__SUCCESS = "DELETE_STEP_REQUEST__SUCCESS";
export const REORDER_STEP_REQUEST = "REORDER_STEP_REQUEST";

//form
export const SET_STEP = "SET_STEP";
export const SET_IMAGE = "SET_IMAGE";
export const REMOVE_IMAGE = "REMOVE_IMAGE";
export const CLEAR_FORM = "CLEAR_FORM";
export const SET_IMAGES = "SET_IMAGES";
export const REORDER_IMAGES = "REORDER_IMAGES";
export const STEP_SUBMIT_CLICK = "STEP_SUBMIT_CLICK";
export const INSERT_IMAGE = "INSERT_IMAGE";
export const DELETE_STEP_VISUALS = "DELETE_STEP_VISUALS";
export const REMOVE_IMAGE_AND_REORDER_STEP = "REMOVE_IMAGE_AND_REORDER_STEP";

//meta
export const SET_ENTITY_META = "SET_ENTITY_META";

//user
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST__SUCCESS = "LOGIN_REQUEST__SUCCESS";
export const LOGIN_REQUEST__FAILURE = "LOGIN_REQUEST__FAILURE";
export const LOGOUT = "LOGOUT";
