export const CREATE_PROCEDURE_REQUEST__SUCCESS = "CREATE_PROCEDURE_REQUEST__SUCCESS";
export const UPDATE_PROCEDURE_REQUEST__SUCCESS = "UPDATE_PROCEDURE_REQUEST__SUCCESS";
export const FETCH_PROCEDURE_REQUEST__SUCCESS = "FETCH_PROCEDURE_REQUEST__SUCCESS";
export const FETCH_PROCEDURE_REQUEST = "FETCH_PROCEDURE_REQUEST";
export const CREATE_PROCEDURE_REQUEST = "CREATE_PROCEDURE_REQUEST";
export const CREATE_PROCEDURE_REQUEST__FAILURE = "CREATE_PROCEDURE_REQUEST__FAILURE";
export const UPDATE_PROCEDURE_REQUEST = "UPDATE_PROCEDURE_REQUEST";
export const UPDATE_PROCEDURE_REQUEST__FAILURE = "UPDATE_PROCEDURE_REQUEST__FAILURE";
