export const FETCH_BUSINESS_PROCEDURES_REQUEST = "FETCH_BUSINESS_PROCEDURES_REQUEST";
export const FETCH_BUSINESS_PROCEDURES_REQUEST__SUCCESS = "FETCH_BUSINESS_PROCEDURES_REQUEST__SUCCESS";
export const CREATE_BUSINESS_REQUEST = "CREATE_BUSINESS_REQUEST";
export const CREATE_BUSINESS_REQUEST__SUCCESS = "CREATE_BUSINESS_REQUEST__SUCCESS";
export const CREATE_BUSINESS_REQUEST__FAILURE = "CREATE_BUSINESS_REQUEST__FAILURE";
export const DELETE_CATEGORY_REQUEST = "DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_REQUEST__SUCCESS = "DELETE_CATEGORY_REQUEST__SUCCESS";
export const DELETE_CATEGORY_REQUEST__FAILURE = "DELETE_CATEGORY_REQUEST__FAILURE";
