export const FETCH_BUSINESS_PROCEDURES_REQUEST = "FETCH_BUSINESS_PROCEDURES_REQUEST";
export const FETCH_BUSINESS_PROCEDURES_REQUEST__SUCCESS = "FETCH_BUSINESS_PROCEDURES_REQUEST__SUCCESS";
export const CREATE_BUSINESS_REQUEST = "CREATE_BUSINESS_REQUEST";
export const CREATE_BUSINESS_REQUEST__SUCCESS = "CREATE_BUSINESS_REQUEST__SUCCESS";
export const CREATE_BUSINESS_REQUEST__FAILURE = "CREATE_BUSINESS_REQUEST__FAILURE";
