export const MAKE_READED = "MAKE_READED";
export const MAKE_READED__SUCCESS = "MAKE_READED__SUCCESS";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_COMMENT__SUCCESS = "DELETE_COMMENT__SUCCESS";
export const DELETE_ALL_COMMENTS = "DELETE_ALL_COMMENTS";
export const DELETE_ALL_COMMENTS__SUCCESS = "DELETE_ALL_COMMENTS__SUCCESS";