export const FETCH_LANGUAGES_REQUEST = "FETCH_LANGUAGES_REQUEST";
export const FETCH_LANGUAGES_REQUEST__SUCCESS = "FETCH_LANGUAGES_REQUEST__SUCCESS";
export const FETCH_LANGUAGES_REQUEST__FAILURE = "FETCH_LANGUAGES_REQUEST__FAILURE";
